import { Mission } from './mission-types';
import { vehicleCatalog } from './vehicle-catalog';

const now = new Date();
const iso = (d: Date) => d.toISOString();
const day = (n: number) => new Date(now.getTime() + n*86400000);

const contacts = [
  { name: 'Alice Martin', email: 'alice@autolux.fr', phone: '+33111111111' },
  { name: 'Bruno Leroy', email: 'bruno@movefleet.fr', phone: '+33122222222' },
  { name: 'Claire Dupont', email: 'claire@hexadrive.fr', phone: '+33133333333' },
];

const convoyeurs = [
  { id: 'drv1', name: 'Paul R.', avatar: 'PR' },
  { id: 'drv2', name: 'Nadia L.', avatar: 'NL' },
  { id: 'drv3', name: 'Hugo C.', avatar: 'HC' },
  { id: 'drv4', name: 'Sofia M.', avatar: 'SM' },
  { id: 'drv5', name: 'Imane T.', avatar: 'IT' },
];

const baseAddress = (city: string) => ({ street: '1 Rue Centrale', city, postalCode: '75000', country: 'France' });

const pickVehicle = (i: number) => vehicleCatalog[i % vehicleCatalog.length];

export const missionsMock: Mission[] = [
  { id: 'M-001', client: { name: 'AutoLux', contact: contacts[0] }, vehicle: { brand: pickVehicle(0).brand, model: pickVehicle(0).model, licensePlate: 'AB-123-CD', category: 'VL', energy: 'Essence', image: pickVehicle(0).image }, departure: { address: baseAddress('Paris'), contact: contacts[0], date: iso(day(-2)), timeSlot: '08:00-10:00' }, arrival: { address: baseAddress('Lyon'), contact: contacts[0], expectedDate: iso(day(-1)), timeSlot: '14:00-16:00' }, status: 'Livrée', priority: 'Normale', distance: 465, estimatedDuration: 320, options: { gpsTracking: true, departureInspection: true, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-5)), updatedAt: iso(day(-1)) },
  { id: 'M-002', client: { name: 'MoveFleet', contact: contacts[1] }, vehicle: { brand: pickVehicle(1).brand, model: pickVehicle(1).model, licensePlate: 'BC-234-DE', category: 'VL', energy: 'Diesel', image: pickVehicle(1).image }, departure: { address: baseAddress('Bordeaux'), contact: contacts[1], date: iso(day(-1)), timeSlot: '09:00-11:00' }, arrival: { address: baseAddress('Nantes'), contact: contacts[1], expectedDate: iso(day(0)), timeSlot: '15:00-18:00' }, status: 'En cours', priority: 'Urgente', distance: 330, estimatedDuration: 250, options: { gpsTracking: true, departureInspection: false, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-4)), updatedAt: iso(day(0)) },
  { id: 'M-003', client: { name: 'HexaDrive', contact: contacts[2] }, vehicle: { brand: pickVehicle(2).brand, model: pickVehicle(2).model, licensePlate: 'CD-345-EF', category: 'VL', energy: 'Électrique', image: pickVehicle(2).image }, departure: { address: baseAddress('Lille'), contact: contacts[2], date: iso(day(0)), timeSlot: '07:00-09:00' }, arrival: { address: baseAddress('Paris'), contact: contacts[2], expectedDate: iso(day(0)), timeSlot: '13:00-15:00' }, status: 'En cours', priority: 'Normale', distance: 220, estimatedDuration: 180, options: { gpsTracking: true, departureInspection: true, arrivalInspection: false, roundTrip: false }, createdAt: iso(day(-3)), updatedAt: iso(day(0)) },
  { id: 'M-004', client: { name: 'AutoLux', contact: contacts[0] }, vehicle: { brand: pickVehicle(3).brand, model: pickVehicle(3).model, licensePlate: 'DE-456-FG', category: 'VL', energy: 'Hybride', image: pickVehicle(3).image }, departure: { address: baseAddress('Paris'), contact: contacts[0], date: iso(day(1)), timeSlot: '10:00-12:00' }, arrival: { address: baseAddress('Lyon'), contact: contacts[0], expectedDate: iso(day(1)), timeSlot: '17:00-19:00' }, status: 'En attente', priority: 'Normale', distance: 465, estimatedDuration: 320, options: { gpsTracking: false, departureInspection: false, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-2)), updatedAt: iso(day(0)) },
  { id: 'M-005', client: { name: 'MoveFleet', contact: contacts[1] }, vehicle: { brand: pickVehicle(4).brand, model: pickVehicle(4).model, licensePlate: 'EF-567-GH', category: 'VL', energy: 'Essence', image: pickVehicle(4).image }, departure: { address: baseAddress('Marseille'), contact: contacts[1], date: iso(day(2)), timeSlot: '06:00-08:00' }, arrival: { address: baseAddress('Toulouse'), contact: contacts[1], expectedDate: iso(day(2)), timeSlot: '13:00-15:00' }, status: 'En attente', priority: 'Urgente', distance: 405, estimatedDuration: 300, options: { gpsTracking: true, departureInspection: true, arrivalInspection: true, roundTrip: true }, createdAt: iso(day(-2)), updatedAt: iso(day(0)) },
  { id: 'M-006', client: { name: 'HexaDrive', contact: contacts[2] }, vehicle: { brand: pickVehicle(5).brand, model: pickVehicle(5).model, licensePlate: 'FG-678-HI', category: 'VL', energy: 'Diesel', image: pickVehicle(5).image }, departure: { address: baseAddress('Dijon'), contact: contacts[2], date: iso(day(-3)), timeSlot: '11:00-13:00' }, arrival: { address: baseAddress('Strasbourg'), contact: contacts[2], expectedDate: iso(day(-2)), timeSlot: '18:00-20:00' }, status: 'Livrée', priority: 'Normale', distance: 335, estimatedDuration: 260, options: { gpsTracking: false, departureInspection: true, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-7)), updatedAt: iso(day(-2)) },
  { id: 'M-007', client: { name: 'AutoLux', contact: contacts[0] }, vehicle: { brand: pickVehicle(6).brand, model: pickVehicle(6).model, licensePlate: 'GH-789-IJ', category: 'VL', energy: 'Essence', image: pickVehicle(6).image }, departure: { address: baseAddress('Nice'), contact: contacts[0], date: iso(day(-4)), timeSlot: '09:00-11:00' }, arrival: { address: baseAddress('Paris'), contact: contacts[0], expectedDate: iso(day(-3)), timeSlot: '17:00-19:00' }, status: 'Livrée', priority: 'Normale', distance: 930, estimatedDuration: 600, options: { gpsTracking: true, departureInspection: false, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-10)), updatedAt: iso(day(-3)) },
  { id: 'M-008', client: { name: 'MoveFleet', contact: contacts[1] }, vehicle: { brand: pickVehicle(7).brand, model: pickVehicle(7).model, licensePlate: 'HI-890-JK', category: 'VL', energy: 'Électrique', image: pickVehicle(7).image }, departure: { address: baseAddress('Rennes'), contact: contacts[1], date: iso(day(-6)), timeSlot: '07:00-09:00' }, arrival: { address: baseAddress('Lyon'), contact: contacts[1], expectedDate: iso(day(-5)), timeSlot: '16:00-18:00' }, status: 'Livrée', priority: 'Normale', distance: 730, estimatedDuration: 520, options: { gpsTracking: true, departureInspection: true, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-9)), updatedAt: iso(day(-5)) },
  { id: 'M-009', client: { name: 'HexaDrive', contact: contacts[2] }, vehicle: { brand: pickVehicle(8).brand, model: pickVehicle(8).model, licensePlate: 'IJ-901-KL', category: 'VL', energy: 'Hybride', image: pickVehicle(8).image }, departure: { address: baseAddress('Paris'), contact: contacts[2], date: iso(day(-1)), timeSlot: '08:00-10:00' }, arrival: { address: baseAddress('Lille'), contact: contacts[2], expectedDate: iso(day(-1)), timeSlot: '14:00-16:00' }, status: 'En cours', priority: 'Urgente', distance: 220, estimatedDuration: 180, options: { gpsTracking: true, departureInspection: true, arrivalInspection: true, roundTrip: false }, createdAt: iso(day(-6)), updatedAt: iso(day(0)) },
  { id: 'M-010', client: { name: 'AutoLux', contact: contacts[0] }, vehicle: { brand: pickVehicle(9).brand, model: pickVehicle(9).model, licensePlate: 'JK-012-LM', category: 'VL', energy: 'Diesel', image: pickVehicle(9).image }, departure: { address: baseAddress('Toulouse'), contact: contacts[0], date: iso(day(-5)), timeSlot: '06:00-08:00' }, arrival: { address: baseAddress('Bordeaux'), contact: contacts[0], expectedDate: iso(day(-4)), timeSlot: '13:00-15:00' }, status: 'En retard', priority: 'Urgente', distance: 245, estimatedDuration: 200, options: { gpsTracking: true, departureInspection: true, arrivalInspection: false, roundTrip: false }, createdAt: iso(day(-8)), updatedAt: iso(day(0)), notes: 'Retard dû à incident trafic' },
];
