project_id = "vdygbqinodzvkdwegvpq"

[functions.generate-tracking-link]
verify_jwt = true

[functions.public-tracking]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.envoyer-invitation]
verify_jwt = true

[functions.envoyer-notification]
verify_jwt = true

[functions.obtenir-itineraire]
verify_jwt = false

[functions.validate-company-insee]
verify_jwt = true

[functions.create-mollie-payment]
verify_jwt = true

[functions.capture-mollie-payment]
verify_jwt = true

[functions.import-from-url]
verify_jwt = true

[functions.issue-mission-photo-url]
verify_jwt = true

[functions.get-directions]
verify_jwt = false

[functions.public-config]
verify_jwt = false

[functions.photo-png]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.generate-quote-pdf]
verify_jwt = true

