project_id = "lucpsjwaglmiejpfxofe"

[functions.generate-tracking-link]
verify_jwt = true

[functions.public-tracking]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.validate-company-insee]
verify_jwt = true

[functions.create-mollie-payment]
verify_jwt = true

[functions.capture-mollie-payment]
verify_jwt = true

[functions.import-from-url]
verify_jwt = true

[functions.issue-mission-photo-url]
verify_jwt = true