// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Use extended Database that augments generated types with quotes until upstream gen includes them
// Use extended Database that augments generated types with Convoiturage tables
import type { Database } from './types.extended';

// Allow overriding via environment variables for safer configuration in web builds
const env = (import.meta as any).env ?? {};
// Important: Never use proxy in production to avoid 405 on static hosts
const useProxy = !!env.DEV && (env.VITE_SUPABASE_USE_PROXY === '1' || !env.VITE_SUPABASE_URL);
const SUPABASE_URL = useProxy
  ? (typeof window !== 'undefined' ? `${window.location.origin}/supabase` : 'http://localhost:8080/supabase')
  : (env.VITE_SUPABASE_URL || "https://lucpsjwaglmiejpfxofe.supabase.co");
// Accept both common names for the anon key
const SUPABASE_ANON_KEY = env.VITE_SUPABASE_ANON_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1Y3BzandhZ2xtaWVqcGZ4b2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTA5NzYsImV4cCI6MjA2OTQ2Njk3Nn0.e3sJec_03qxC9C4aHpv-fLQ36wz7c_76xePBv76Ydkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});